# Generated by Django 5.2.3 on 2025-10-04 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0002_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
