# Generated by Django 5.2.3 on 2025-06-23 15:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                ("slug", models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("imdb_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                (
                    "youtube_id",
                    models.CharField(blank=True, max_length=100, null=True, unique=True),
                ),
                ("omdb_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("booking_start_date", models.DateField()),
                ("booking_end_date", models.DateField()),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="cinema.film",
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_start_date"],
            },
        ),
        migrations.CreateModel(
            name="PlayDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_dates",
                        to="cinema.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
                "unique_together": {("booking", "date", "time")},
            },
        ),
    ]
