# Generated by Django 5.2.3 on 2025-06-21 11:25
import json
from django.db import migrations


def load_films(apps, schema_editor):
    Film = apps.get_model('cinema', 'Film')
    with open('cinema/fixtures/films.json', 'r') as file:
        films = json.load(file)

    for film_data in films:
        Film.objects.create(
            title=film_data['title'],
            youtube_id=film_data['youtube_id'],
            imdb_id=film_data['imdb_id']
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_films),
    ]
