# Generated by Django 5.2.3 on 2025-06-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_auto_20250623_1119"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PlayDate",
            new_name="ScreeningTime",
        ),
        migrations.AlterModelOptions(
            name="film",
            options={"ordering": ["title"]},
        ),
    ]
