# Generated by Django 5.2.3 on 2025-06-22 14:16
from datetime import datetime

from django.db import migrations
from django.utils.text import slugify


def load_bookings(apps, schema_editor):
    Film = apps.get_model("cinema", "Film")
    Booking = apps.get_model("cinema", "Booking")

    # Load films and bookings from the JSON file
    import json

    from django.conf import settings

    with open(settings.BASE_DIR / "cinema" / "fixtures" / "bookings.json") as f:
        data = json.load(f)

    count = 0

    for film_data in data:
        film, created = Film.objects.get_or_create(
            title=film_data["title"], slug=slugify(film_data["title"])
        )
        if created:
            count += 1
        if film:
            Booking.objects.create(
                film=film,
                booking_start_date=datetime.strptime(
                    film_data["booking_start_date"], "%Y-%m-%d"
                ).date(),
                booking_end_date=datetime.strptime(
                    film_data["booking_end_date"], "%Y-%m-%d"
                ).date(),
                confirmed=film_data.get("confirmed", False),
            )
    if count:
        print(f"There are {count} films missing from films.json")


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_film_omdb_json_booking"),
    ]

    operations = [
        migrations.RunPython(load_bookings),
    ]
