# Generated by Django 5.2.3 on 2025-06-22 14:16
from django.db import migrations
from datetime import datetime
from django.utils.text import slugify

def load_bookings(apps, schema_editor):
    Film = apps.get_model('cinema', 'Film')
    Booking = apps.get_model('cinema', 'Booking')

    # Load films and bookings from the JSON file
    import json
    from django.conf import settings

    with open(settings.BASE_DIR / 'cinema' / 'fixtures' / 'bookings.json') as f:
        data = json.load(f)

    for film_data in data:
        film, created = Film.objects.get_or_create(title=film_data['title'], slug=slugify(film_data['title']))
        if film:
            Booking.objects.create(
                film=film,
                booking_start_date=datetime.strptime(film_data['booking_start_date'], '%Y-%m-%d').date(),
                booking_end_date=datetime.strptime(film_data['booking_end_date'], '%Y-%m-%d').date(),
                confirmed=film_data.get('confirmed', False)
            )

class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_film_omdb_json_booking'),
    ]

    operations = [
        migrations.RunPython(load_bookings),
    ]
