# Generated by Django 5.2.3 on 2025-06-22 14:16
import json
from datetime import datetime

from django.conf import settings
from django.db import migrations


def load_bookings(apps, schema_editor):
    Film = apps.get_model("cinema", "Film")
    Booking = apps.get_model("cinema", "Booking")
    PlayDate = apps.get_model("cinema", "PlayDate")

    with open(settings.BASE_DIR / "cinema" / "fixtures" / "bookings.json") as f:
        data = json.load(f)

    count = 0

    for film_data in data:
        film, created = Film.objects.get_or_create(title=film_data["title"])
        if created:
            count += 1
        if film:
            booking = Booking.objects.create(
                film=film,
                booking_start_date=datetime.strptime(
                    film_data["booking_start_date"], "%Y-%m-%d"
                ).date(),
                booking_end_date=datetime.strptime(
                    film_data["booking_end_date"], "%Y-%m-%d"
                ).date(),
                confirmed=film_data.get("confirmed", False),
            )
            if play_dates := film_data.get("play_dates"):
                for playdate in play_dates:
                    PlayDate.objects.create(
                        booking=booking,
                        date=datetime.strptime(playdate["date"], "%Y-%m-%d").date(),
                        time=datetime.strptime(playdate["time"], "%H:%M:%S").time(),
                    )

    if count:
        print(f"There are {count} films missing from films.json")


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_film_omdb_json_booking_playdate"),
    ]

    operations = [
        migrations.RunPython(load_bookings),
    ]
