# Generated by Django 5.2.3 on 2025-06-23 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_auto_20250622_1016"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_dates",
                        to="cinema.film",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "time"],
                "unique_together": {("film", "date", "time")},
            },
        ),
    ]
