# Generated by Django 5.2.3 on 2025-06-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_auto_20250624_0715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screeningtime",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screening_times",
                to="cinema.booking",
            ),
        ),
    ]
