# Generated by Django 5.2.3 on 2025-06-24 23:16
import time

from django.db import migrations

from cinema.services import OpenMovieDatabaseService


def populate_omdb_info(apps, schema_editor):
    """
    Populate the omdb_info field in the Movie model with data from the Open Movie Database API.
    """
    Movie = apps.get_model("cinema", "Film")
    service = OpenMovieDatabaseService()

    for movie in Movie.objects.all():
        print("Processing movie:", movie.title)
        try:
            omdb_data = service.get_movie_details(imdb_id=movie.imdb_id)
            movie.omdb_json = omdb_data
            movie.save(update_fields=["omdb_json"])
            time.sleep(1)
        except Exception as e:
            print(f"Error fetching data for {movie.title}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0005_alter_screeningtime_booking"),
    ]

    operations = [
        migrations.RunPython(populate_omdb_info, reverse_code=migrations.RunPython.noop),
    ]
