# Generated by Django 5.2.3 on 2025-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_squashed_0005_alter_screeningtime_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="prime_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
