# Generated by Django 5.2.3 on 2025-09-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0006_film_prime_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-event_start_date"],
            },
        ),
    ]
