# Generated by Django 5.2.3 on 2025-09-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
