# Generated by Django 5.2.3 on 2025-10-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0008_event_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="prime_link",
        ),
    ]
