# Generated by Django 5.2.3 on 2025-10-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0009_remove_film_prime_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ticket_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
