# Generated by Django 5.2.3 on 2025-10-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0010_booking_ticket_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["booking_start_date"]},
        ),
    ]
