# Generated by Django 5.2.3 on 2025-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0011_alter_booking_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
