# Generated by Django 5.2.3 on 2025-10-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0012_alter_event_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="ticket_link",
        ),
    ]
