# Generated by Django 5.2.3 on 2025-10-11 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0013_remove_booking_ticket_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="omdb_json",
        ),
    ]
