# Generated by Django 5.2.3 on 2025-10-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0014_remove_film_omdb_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="film",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "General Audiences"),
                    ("PG", "Parental Guidance Suggested"),
                    ("PG-13", "Parents Strongly Cautioned"),
                    ("R", "Restricted"),
                    ("NC-17", "Adults Only"),
                ],
                default="PG",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="runtime",
            field=models.PositiveIntegerField(
                blank=True, help_text="Runtime in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="genres",
            field=models.ManyToManyField(blank=True, related_name="films", to="cinema.filmgenre"),
        ),
    ]
