# Generated by Django 5.2.3 on 2025-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0015_filmgenre_film_poster_url_film_rating_film_runtime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="terms_guarantee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="terms_percentage",
            field=models.DecimalField(decimal_places=2, default=0, help_text="0–100", max_digits=5),
        ),
    ]
