# Generated by Django 5.2.3 on 2025-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0016_booking_terms_guarantee_booking_terms_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("GA", "General Admission"),
                            ("MT", "Matinee"),
                            ("SE", "Special Event Screening"),
                        ],
                        default="GA",
                        max_length=2,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
