# Generated by Django 5.2.3 on 2025-10-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0017_ticketrate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticketrate",
            name="name",
        ),
        migrations.AlterField(
            model_name="ticketrate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("GA", "General Admission"),
                    ("MT", "Matinee"),
                    ("SE", "Special Event Screening"),
                ],
                default="GA",
                max_length=2,
                unique=True,
            ),
        ),
    ]
