# Generated by Django 5.2.3 on 2025-11-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0018_remove_ticketrate_name_alter_ticketrate_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketrate",
            name="member_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name="ticketrate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("GA", "General Admission"),
                    ("MT", "Matinee"),
                    ("SE", "Special Event Screening"),
                    ("DF", "Double Feature"),
                ],
                default="GA",
                max_length=2,
                unique=True,
            ),
        ),
    ]
