# Generated by Django 5.2.3 on 2025-11-11 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0019_ticketrate_member_price_alter_ticketrate_rate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="auditorium",
            field=models.CharField(
                choices=[
                    ("South Auditorium", "South Auditorium"),
                    ("North Auditorium", "North Auditorium"),
                ],
                default="South Auditorium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="film",
            name="square_catalog_item_id",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="square_variation_id",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="ticketrate",
            name="rate_type",
            field=models.CharField(
                choices=[
                    ("EA", "Evening Admission"),
                    ("GA", "General Admission"),
                    ("MT", "Matinee Admission"),
                ],
                default="GA",
                max_length=2,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ticket_number", models.CharField(max_length=20, unique=True)),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cinema.ticketrate"
                    ),
                ),
                (
                    "screening_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tickets",
                        to="cinema.screeningtime",
                    ),
                ),
            ],
        ),
    ]
