# Generated by Django 5.2.3 on 2025-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0020_booking_auditorium_film_square_catalog_item_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketrate",
            name="rate_type",
            field=models.CharField(
                choices=[("EA", "Evening Admission"), ("MT", "Matinee Admission")],
                default="EA",
                max_length=2,
                unique=True,
            ),
        ),
    ]
