# Generated by Django 5.2.3 on 2025-11-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0021_alter_ticketrate_rate_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="film",
            old_name="square_catalog_item_id",
            new_name="square_item_id",
        ),
    ]
