# Generated by Django 5.2.3 on 2025-11-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0022_rename_square_catalog_item_id_film_square_item_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="square_item_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="square_item_id",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="film",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
