# Generated by Django 5.2.3 on 2025-11-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0023_remove_film_square_item_id_booking_square_item_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="square_item_id",
        ),
        migrations.AddField(
            model_name="film",
            name="square_item_id",
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
