# Generated by Django 5.2.3 on 2025-11-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0024_remove_booking_square_item_id_film_square_item_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketrate",
            name="square_item_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
