# Generated by Django 5.2.3 on 2025-11-12 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0026_remove_film_square_item_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
