# Generated by Django 5.2.3 on 2025-11-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0027_delete_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="square_item_id",
            new_name="square_id",
        ),
        migrations.AddField(
            model_name="booking",
            name="square_version",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="square_variation_version",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
