# Generated by Django 5.2.3 on 2025-11-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0028_rename_square_item_id_booking_square_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screeningtime",
            name="open_captions",
            field=models.BooleanField(default=False),
        ),
    ]
