# Generated by Django 5.2.3 on 2025-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0029_screeningtime_open_captions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="square_id",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="square_version",
        ),
        migrations.RemoveField(
            model_name="screeningtime",
            name="square_variation_id",
        ),
        migrations.RemoveField(
            model_name="screeningtime",
            name="square_variation_version",
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="member_ticket_end_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="member_ticket_start_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="regular_ticket_end_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="screeningtime",
            name="regular_ticket_start_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
