# Generated by Django 5.2.3 on 2025-12-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0030_remove_booking_square_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screeningtime",
            name="member_ticket_end_number",
        ),
        migrations.RemoveField(
            model_name="screeningtime",
            name="member_ticket_start_number",
        ),
        migrations.RemoveField(
            model_name="screeningtime",
            name="regular_ticket_end_number",
        ),
        migrations.RemoveField(
            model_name="screeningtime",
            name="regular_ticket_start_number",
        ),
    ]
