# Generated by Django 5.2.3 on 2025-12-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_blogpost_products"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="blog.blogauthor"
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="blog.blogcategory"
            ),
        ),
    ]
