# Generated by Django 5.2.3 on 2025-11-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("square_integration", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
