# Generated by Django 5.2.3 on 2025-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("square_integration", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("square_id", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
