# Generated by Django 5.2.3 on 2025-11-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("square_integration", "0004_taxrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxrate",
            name="percentage",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
