# Generated by Django 5.2.3 on 2025-11-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("square_integration", "0005_alter_taxrate_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogcategory",
            name="parent",
        ),
        migrations.DeleteModel(
            name="TaxRate",
        ),
        migrations.DeleteModel(
            name="CatalogCategory",
        ),
    ]
