# Generated by Django 5.2.3 on 2025-11-16 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("square_integration", "0006_remove_catalogcategory_parent_delete_taxrate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquareItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("square_id", models.CharField(blank=True, max_length=255, null=True)),
                ("version", models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "squareitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="square_integration.squareitem",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("percentage", models.DecimalField(decimal_places=3, max_digits=5)),
                ("active", models.BooleanField(default=True)),
            ],
            bases=("square_integration.squareitem",),
        ),
        migrations.CreateModel(
            name="CatalogCategory",
            fields=[
                (
                    "squareitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="square_integration.squareitem",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="subcategories",
                        to="square_integration.catalogcategory",
                    ),
                ),
            ],
            bases=("square_integration.squareitem",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "squareitem_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="square_integration.squareitem",
                    ),
                ),
                ("name", models.CharField(default="Regular Item", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="This is the default variation of this item", null=True
                    ),
                ),
                ("abbreviation", models.CharField(blank=True, max_length=10, null=True)),
                ("is_taxable", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="square_integration.catalogcategory"
                    ),
                ),
                (
                    "tax_rates",
                    models.ManyToManyField(
                        blank=True, related_name="items", to="square_integration.taxrate"
                    ),
                ),
            ],
            bases=("square_integration.squareitem",),
        ),
    ]
