# Generated by Django 5.2.3 on 2025-11-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("square_integration", "0007_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="item",
            name="squareitem_ptr",
        ),
        migrations.RemoveField(
            model_name="item",
            name="tax_rates",
        ),
        migrations.RemoveField(
            model_name="taxrate",
            name="squareitem_ptr",
        ),
        migrations.DeleteModel(
            name="CatalogCategory",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="SquareItem",
        ),
        migrations.DeleteModel(
            name="TaxRate",
        ),
    ]
