# Generated by Django 5.2.3 on 2025-11-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MembershipBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MembershipType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("duration_months", models.PositiveIntegerField(default=12)),
                (
                    "limit_per_customer",
                    models.PositiveIntegerField(default=0, help_text="0 = no limit"),
                ),
                ("taxable", models.BooleanField(default=False)),
                ("price_cents", models.PositiveIntegerField(help_text="Price in cents")),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("square_item_id", models.CharField(blank=True, default="", max_length=64)),
                ("square_item_version", models.BigIntegerField(blank=True, null=True)),
                ("square_variation_id", models.CharField(blank=True, default="", max_length=64)),
                ("square_variation_version", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "benefits",
                    models.ManyToManyField(
                        blank=True,
                        related_name="membership_types",
                        to="memberships.membershipbenefit",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
    ]
