# Generated by Django 5.2.3 on 2025-11-12 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0001_initial"),
        ("square_integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiptype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="limit_per_customer",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_item_version",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_variation_id",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_variation_version",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="taxable",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="membershiptype",
            name="square_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="square_integration.category",
            ),
        ),
    ]
