# Generated by Django 5.2.3 on 2025-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0002_remove_membershiptype_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="square_item_variation_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
