# Generated by Django 5.2.3 on 2025-11-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0003_membershiptype_square_item_variation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_category",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_item_id",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_item_variation_id",
        ),
    ]
