# Generated by Django 5.2.3 on 2025-11-13 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0004_remove_membershiptype_square_category_and_more"),
        ("square_integration", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiptype",
            name="slug",
        ),
        migrations.AddField(
            model_name="membershiptype",
            name="square_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="square_integration.catalogcategory",
            ),
        ),
        migrations.AddField(
            model_name="membershiptype",
            name="square_item_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
