# Generated by Django 5.2.3 on 2025-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0005_remove_membershiptype_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="square_item_variation_id",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
