# Generated by Django 5.2.3 on 2025-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0006_membershiptype_square_item_variation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershiptype",
            name="square_payment_link",
            field=models.URLField(blank=True),
        ),
    ]
