# Generated by Django 5.2.3 on 2025-11-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0007_membershiptype_square_payment_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershiptype",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="membershiptype",
            name="square_category",
        ),
        migrations.DeleteModel(
            name="MembershipBenefit",
        ),
        migrations.DeleteModel(
            name="MembershipType",
        ),
    ]
