# Generated by Django 5.2.3 on 2025-06-19 01:23
import json

from django.db import migrations


def load_authors(apps, schema_editor):
    BlogAuthor = apps.get_model("blog", "BlogAuthor")
    with open("blog/fixtures/authors.json", encoding="utf-8") as f:
        authors = json.load(f)
        for author in authors:
            BlogAuthor.objects.create(
                first_name=author["first_name"], last_name=author["last_name"]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_authors),
    ]
