# Generated by Django 5.2.3 on 2025-06-19 01:30
import json
from django.db import migrations

def load_categories(apps, schema_editor):
    BlogCategory = apps.get_model('blog', 'BlogCategory')
    with open('blog/fixtures/categories.json', 'r') as file:
        categories = json.load(file)
        for category in categories:
            new_category = BlogCategory.objects.create(**category)
            # Ensure the slug is generated if not provided
            new_category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory'),
    ]

    operations = [
        migrations.RunPython(load_categories),
    ]
