# Generated by Django 5.2.3 on 2025-06-19 01:36
import json

from django.db import migrations


def load_blog_posts(apps, schema_editor):
    BlogPost = apps.get_model("blog", "BlogPost")
    BlogAuthor = apps.get_model("blog", "BlogAuthor")
    BlogCategory = apps.get_model("blog", "BlogCategory")

    author = BlogAuthor.objects.get(first_name="Rick", last_name="Douglas")
    category = BlogCategory.objects.get(name="Rick's Reviews")

    with open("blog/fixtures/blog.json") as file:
        blog_posts = json.load(file)
        for post in blog_posts:
            BlogPost.objects.create(
                title=post["title"],
                subtitle=post["subtitle"],
                author=author,
                category=category,
                post_date=post["date"],
                content=post["content"],
            )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_blogpost"),
    ]

    operations = [
        migrations.RunPython(load_blog_posts),
    ]
