# Generated by Django 5.2.3 on 2025-07-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_blogcategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
