# Generated by Django 5.2.3 on 2025-10-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_blogpost_products"),
    ]

    operations = []
