# Generated by Django 5.2.3 on 2026-01-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_blogpost_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={"verbose_name_plural": "Blog categories"},
        ),
    ]
