# Generated by Django 5.2.3 on 2025-11-14 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("square_integration", "0004_taxrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="square_integration.catalogcategory",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variations",
                to="inventory.inventoryitem",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="tax_rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="square_integration.taxrate",
            ),
        ),
    ]
