# Generated by Django 5.2.3 on 2025-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventoryitem_category_inventoryitem_parent_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="square_item_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="square_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
