# Generated by Django 5.2.3 on 2025-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_inventoryitem_square_item_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
