# Generated by Django 5.2.3 on 2025-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_inventoryitem_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="price",
            new_name="price_cents",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
