# Generated by Django 5.2.3 on 2025-11-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_rename_price_inventoryitem_price_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="square_item_variation_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="square_variation_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
