# Generated by Django 5.2.3 on 2025-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_inventoryitem_square_item_variation_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="square_variation_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="square_version",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
