# Generated by Django 5.2.3 on 2025-11-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_inventoryitem_square_variation_version_and_more"),
        ("square_integration", "0005_alter_taxrate_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="category",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="inventory_items",
                to="square_integration.catalogcategory",
            ),
        ),
    ]
