# Generated by Django 5.2.3 on 2025-11-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_remove_inventoryitem_category_inventoryitem_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventoryitem",
            old_name="category",
            new_name="categories",
        ),
    ]
