# Generated by Django 5.2.3 on 2025-11-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_rename_category_inventoryitem_categories"),
        ("square_integration", "0005_alter_taxrate_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="inventory_items", to="square_integration.catalogcategory"
            ),
        ),
    ]
