# Generated by Django 5.2.3 on 2025-11-16 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_inventoryitem_categories"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InventoryItem",
        ),
    ]
